import {
    createAdvance,
    editAdvance,
} from '../../_services/advance.service';
import { validateAdvance } from './model';

export const createAdvanceEvent = async (body) => {
    validateAdvance(body);
    return await createAdvance(body);
}

export const editAdvanceEvent = async (id, body) => {
    validateAdvance(body);
    return await editAdvance(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */