import {
    createAdvance,
    editAdvance,
    approveAdvance,
    declineAdvance
} from '../../_services/advance.service';
import { validateAdvance } from './model';
import { AdvanceType } from './type';

export const createAdvanceEvent = async (body: AdvanceType) => {
    validateAdvance(body);
    return await createAdvance(body);
}

export const editAdvanceEvent = async (id: string, body: AdvanceType) => {
    validateAdvance(body);
    return await editAdvance(id, body);
}

export const approveAdvanceEvent = async (id: string) => {
    return await approveAdvance(id);
}

export const declineAdvanceEvent = async (id: string) => {
    return await declineAdvance(id);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */