import {
    findAllAdvance,
    findAdvanceById,
    findAllAdvancePaged,
} from '../../_services/advance.service';

export const findAllAdvanceEvent = async () => {
    return await findAllAdvance();
}

export const findAdvanceByIdEvent = async (id) => {
    return await findAdvanceById(id);
}

export const findAllAdvancePagedEvent = async (page, limit = 8) => {
    return await findAllAdvancePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */