import { AdvanceType } from "./type";

export const validateAdvance = (body: AdvanceType) => {
    //const {  } = body;
}

export const transformEntityAdvance = (entity: AdvanceType) => {
    let newEnt = {...entity}
    if(typeof newEnt.employee === 'object') newEnt.employee = newEnt.employee?.uuid;
    if(typeof newEnt.state === 'object') newEnt.state = newEnt.state?.cod;
    return newEnt;
}

export const buildEmptyAdvance = (): AdvanceType => {
    return {
        uuid: '',
        created_date: new Date(),
        value: 0,
        cost: 0,
        employee: '',
        state: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */