export const validateAdvance = (body) => {
    //const {  } = body;
}

export const transformEntityAdvance = (entity) => {
    let newEnt = {...entity}
    newEnt.employee = newEnt.employee?.uuid;
    newEnt.state = newEnt.state?.cod;
    return newEnt;
}

export const buildEmptyAdvance = () => {
    return {
        uuid: '',
        created_date: '',
        approved_date: '',
        declined_date: '',
        value: '',
        cost: '',
        employee: '',
        state: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */