import { handleFetch, GET_OPTIONS, POST_OPTIONS } from './base.service';


const BASE_PATH = '/advance-period';

export const findAllAdvancePeriod = async () => {
    return await handleFetch(`${BASE_PATH}/all`, GET_OPTIONS, null);
}

export const findAllAdvancePeriodByEnterprise = async (enterprise: number) => {
    return await handleFetch(`${BASE_PATH}/all/enterprise/${enterprise}`, GET_OPTIONS, null);
}

export const findAdvancePeriodById = async (id: any) => {
    return await handleFetch(`${BASE_PATH}/id/${id}`, GET_OPTIONS, null);
}

export const createAdvancePeriod = async (body: any) => {
    return await handleFetch(`${BASE_PATH}/finish-create`, POST_OPTIONS, body);
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */