import { AmountCreateTransaction } from '../_events/amount/type';
import { handleFetch, GET_OPTIONS, POST_OPTIONS, PUT_OPTIONS } from './base.service';


const BASE_PATH = '/amount';

export const findAllAmount = async () => {
    return await handleFetch(`${BASE_PATH}/all`, GET_OPTIONS, null);
}

export const findAmountById = async (id: any) => {
    return await handleFetch(`${BASE_PATH}/id/${id}`, GET_OPTIONS, null);
}

export const createAmount = async (body: any) => {
    return await handleFetch(`${BASE_PATH}/create`, POST_OPTIONS, body);
}

export const editAmount = async (id: any, body: any) => {
    return await handleFetch(`${BASE_PATH}/edit/${id}`, PUT_OPTIONS, body);
}

export const findAllAmountPaged = async (page: any, limit: any) => {
    return await handleFetch(`${BASE_PATH}/all-paged/${page}/${limit}`, GET_OPTIONS, null);
}

export const createAmountTransaction = async (body: AmountCreateTransaction) => {
    return await handleFetch(`${BASE_PATH}/create-transaction`, POST_OPTIONS, body);
}

export const findAllAmountByEnterprise = async (enterprise: number) => {
    return await handleFetch(`${BASE_PATH}/enterprise/${enterprise}`, GET_OPTIONS, null);
}

export const findAllAmountByEmployee = async (employee: string) => {
    return await handleFetch(`${BASE_PATH}/employee/${employee}`, GET_OPTIONS, null);
}


/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */