import { LoginType } from '../_events/login/type.js';
import { handleFetch, POST_OPTIONS } from './base.service';


const BASE_PATH = '/login';

export const loginUser = async (body: LoginType) => {
    return await handleFetch(`${BASE_PATH}/user`, POST_OPTIONS, body);
}

export const loginEmployee = async (body: LoginType) => {
    return await handleFetch(`${BASE_PATH}/employee`, POST_OPTIONS, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */