import { handleFetch, POST_OPTIONS } from './base.service.js';


const BASE_PATH = '/login';

export const loginUser = async (body) => {
    return await handleFetch(`${BASE_PATH}/user`, POST_OPTIONS, body);
}

export const loginEmployee = async (body) => {
    return await handleFetch(`${BASE_PATH}/employee`, POST_OPTIONS, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */