import {
    createRange,
    editRange,
    activateRange,
    blockRange
} from '../../_services/range.service';
import { validateRange } from './model';
import { RangeType } from './type';

export const createRangeEvent = async (body: RangeType) => {
    validateRange(body);
    return await createRange(body);
}

export const editRangeEvent = async (id: string, body: RangeType) => {
    validateRange(body);
    return await editRange(id, body);
}

export const activateRangeEvent = async (id: string) => {
    return await activateRange(id);
}

export const blockRangeEvent = async (id: string) => {
    return await blockRange(id);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */