import {
    createRange,
    editRange,
} from '../../_services/range.service';
import { validateRange } from './model';

export const createRangeEvent = async (body) => {
    validateRange(body);
    return await createRange(body);
}

export const editRangeEvent = async (id, body) => {
    validateRange(body);
    return await editRange(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */