import {
    findAllRange,
    findRangeById,
    findAllRangePaged,
} from '../../_services/range.service';

export const findAllRangeEvent = async () => {
    return await findAllRange();
}

export const findRangeByIdEvent = async (id) => {
    return await findRangeById(id);
}

export const findAllRangePagedEvent = async (page, limit = 8) => {
    return await findAllRangePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */