import {
    findAllRange,
    findRangeById,
    findAllRangePaged,
    findAllRangeByEnterprise,
} from '../../_services/range.service';

export const findAllRangeEvent = async () => {
    return await findAllRange();
}

export const findRangeByIdEvent = async (id: string) => {
    return await findRangeById(id);
}

export const findAllRangePagedEvent = async (page: number, limit = 8) => {
    return await findAllRangePaged(page, limit);
}

export const findAllRangeByEnterpriseEvent = async (enterprise: number) => {
    return await findAllRangeByEnterprise(enterprise);
}


/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */