export const validateRange = (body) => {
    //const {  } = body;
}

export const transformEntityRange = (entity) => {
    let newEnt = {...entity}
    newEnt.enterprise = newEnt.enterprise?.id;
    return newEnt;
}

export const buildEmptyRange = () => {
    return {
        uuid: '',
        id: '',
        enterprise: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */