import {
    createAdvancePeriod,
} from '../../_services/advance_period.service';
import { validateAdvancePeriod } from './model';
import { AdvancePeriodType } from './type';

export const createAdvancePeriodEvent = async (body: AdvancePeriodType) => {
    validateAdvancePeriod(body);
    return await createAdvancePeriod(body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */