import {
    findAllAdvancePeriodByEnterprise
} from '../../_services/advance_period.service';

export const findAllAdvancePeriodByEnterpriseEvent = async (enterprise: number) => {
    return await findAllAdvancePeriodByEnterprise(enterprise);
}


/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */