import {
    createAdvanceState,
    editAdvanceState,
} from '../../_services/advance_state.service';
import { validateAdvanceState } from './model';
import { AdvanceStateType } from './type';

export const createAdvanceStateEvent = async (body: AdvanceStateType) => {
    validateAdvanceState(body);
    return await createAdvanceState(body);
}

export const editAdvanceStateEvent = async (id: string, body: AdvanceStateType) => {
    validateAdvanceState(body);
    return await editAdvanceState(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */