import {
    findAllAdvanceState,
    findAdvanceStateById,
    findAllAdvanceStatePaged,
} from '../../_services/advance_state.service';

export const findAllAdvanceStateEvent = async () => {
    return await findAllAdvanceState();
}

export const findAdvanceStateByIdEvent = async (id: string) => {
    return await findAdvanceStateById(id);
}

export const findAllAdvanceStatePagedEvent = async (page: number, limit: number = 8) => {
    return await findAllAdvanceStatePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */