import { AdvanceStateType } from "./type";

export const validateAdvanceState = (body: AdvanceStateType) => {
    //const {  } = body;
}

export const transformEntityAdvanceState = (entity: AdvanceStateType) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyAdvanceState = (): AdvanceStateType => {
    return {
        cod: '',
        name: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */