import { BankAccountType } from "./type";

export const validateBankAccountType = (body: BankAccountType) => {
    const { cod, name } = body;
    if(cod === '' || cod === undefined) throw new Error(`Cod vacío`);
    if(name === '' || name === undefined) throw new Error(`Nombre vacío`);
}

export const transformEntityBankAccountType = (entity: BankAccountType) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyBankAccountType = (): BankAccountType => {
    return {
        cod: '',
        name: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */