import { BankType } from "./type";

export const validateBank = (body: BankType) => {
    //const {  } = body;
}

export const transformEntityBank = (entity: BankType) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyBank = () => {
    return {
        cod: '',
        name: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */