import {
    createUserRol,
    editUserRol,
} from '../../_services/user_rol.service';
import { validateUserRol } from './model';

export const createUserRolEvent = async (body) => {
    validateUserRol(body);
    return await createUserRol(body);
}

export const editUserRolEvent = async (id, body) => {
    validateUserRol(body);
    return await editUserRol(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */