import {
    createBankMessages,
    editBankMessages,
} from '../../_services/bank_messages.service';
import { validateBankMessages } from './model';
import { BankMessages } from './type';

export const createBankMessagesEvent = async (body: BankMessages) => {
    validateBankMessages(body);
    return await createBankMessages(body);
}

export const editBankMessagesEvent = async (id: string, body: BankMessages) => {
    validateBankMessages(body);
    return await editBankMessages(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */