import {
    findAllBankMessages,
    findBankMessagesById,
    findAllBankMessagesPaged,
} from '../../_services/bank_messages.service';

export const findAllBankMessagesEvent = async () => {
    return await findAllBankMessages();
}

export const findBankMessagesByIdEvent = async (id: string) => {
    return await findBankMessagesById(id);
}

export const findAllBankMessagesPagedEvent = async (page: number, limit: number = 8) => {
    return await findAllBankMessagesPaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */