import { BankMessages } from "./type";

export const validateBankMessages = (body: BankMessages) => {
    const { cod, message, bank } = body;
    if(cod === '' || cod === undefined) throw new Error(`Código vacío`);
    if(message === '' || message === undefined) throw new Error(`Mensaje vacío`);
    if(bank === '' || bank === undefined) throw new Error(`Banco vacío`);
}

export const transformEntityBankMessages = (entity: BankMessages) => {
    let newEnt = {...entity}
    if(newEnt.bank && typeof newEnt.bank === 'object' && newEnt.bank.cod) newEnt.bank = newEnt.bank?.cod;
    return newEnt;
}

export const buildEmptyBankMessages = (): BankMessages => {
    return {
        cod: '',
        message: '',
        bank: ''
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */