import {
    createAmount,
    editAmount,
} from '../../_services/amount.service';
import { validateAmount } from './model';
import { Amount } from './type';

export const createAmountEvent = async (body: Amount) => {
    validateAmount(body);
    return await createAmount(body);
}

export const editAmountEvent = async (id: string, body: Amount) => {
    validateAmount(body);
    return await editAmount(id, body);
}


/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */