import {
    createAmount,
    editAmount,
    createAmountTransaction,
} from '../../_services/amount.service';
import { validateAmount, validateTransactionAmount } from './model';
import { Amount, AmountCreateTransaction } from './type';

export const createAmountEvent = async (body: Amount) => {
    validateAmount(body);
    return await createAmount(body);
}

export const editAmountEvent = async (id: string, body: Amount) => {
    validateAmount(body);
    return await editAmount(id, body);
}

export const createAmountTransactionEvent = async (body: AmountCreateTransaction) => {
    validateTransactionAmount(body);
    return await createAmountTransaction(body);
}


/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */