import {
    findAllAmount,
    findAmountById,
    findAllAmountPaged,
    findAllAmountByEmployee,
    findAllAmountByEnterprise
} from '../../_services/amount.service';

export const findAllAmountEvent = async () => {
    return await findAllAmount();
}

export const findAmountByIdEvent = async (id: string) => {
    return await findAmountById(id);
}

export const findAllAmountPagedEvent = async (page: number, limit: number = 8) => {
    return await findAllAmountPaged(page, limit);
}

export const findAllAmountByEmployeeEvent = async (id: string) => {
    return await findAllAmountByEmployee(id);
}

export const findAllAmountByEnterpriseEvent = async (id: number) => {
    return await findAllAmountByEnterprise(id);
}


/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */