import { Amount } from "./type";

export const validateAmount = (body: Amount) => {
    //const {  } = body;
}

export const transformEntityAmount = (entity: Amount) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyAmount = (): Amount => {
    return {
        uuid: '',
        value: 0,
        cost: 0,
        active: 0,
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */