export const validateAmount = (body) => {
    //const {  } = body;
}

export const transformEntityAmount = (entity) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyAmount = () => {
    return {
        uuid: '',
        value: '',
        cost: '',
        active: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */