import { Amount, AmountCreateTransaction } from "./type";

export const validateAmount = (body: Amount) => {
    const { value, cost } = body;
    if(value === 0 || value === undefined) throw new Error(`Valor vacío`);
    if(cost === 0 || cost === undefined) throw new Error(`Costo vacío`);
}

export const validateTransactionAmount = (body: AmountCreateTransaction) => {
    const { range } = body;
    validateAmount(body);
    if(range === '' || range === undefined) throw new Error(`Rango vacío`);
}

export const transformEntityAmount = (entity: Amount) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyAmount = (): Amount => {
    return {
        uuid: '',
        value: 0,
        cost: 0,
        active: 1,
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */