import { Fintech } from "./type";

export const validateFintech = (body: Fintech) => {
    const { cod, name } = body;
    if(cod === '' || cod === undefined) throw new Error(`Cod vacío`);
    if(name === '' || name === undefined) throw new Error(`Nombre vacío`);
}

export const transformEntityFintech = (entity: Fintech) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyFintech = (): Fintech => {
    return {
        cod: '',
        name: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */