export const validateUser = (body) => {
    //const {  } = body;
}

export const transformEntityUser = (entity) => {
    let newEnt = {...entity}
    newEnt.enterprise = newEnt.enterprise?.id;
    newEnt.rol = newEnt.rol?.cod;
    return newEnt;
}

export const buildEmptyUser = () => {
    return {
        uuid: '',
        name: '',
        email: '',
        login: '',
        password: '',
        active: '',
        enterprise: '',
        rol: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */