import {
    createMessages,
    editMessages,
} from '../../_services/messages.service';
import { validateMessages } from './model';
import { Messages } from './type';

export const createMessagesEvent = async (body: Messages) => {
    validateMessages(body);
    return await createMessages(body);
}

export const editMessagesEvent = async (id: string, body: Messages) => {
    validateMessages(body);
    return await editMessages(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */