import {
    createEnterprise,
    editEnterprise,
} from '../../_services/enterprise.service';
import { validateEnterprise } from './model';

export const createEnterpriseEvent = async (body: any) => {
    validateEnterprise(body);
    return await createEnterprise(body);
}

export const editEnterpriseEvent = async (id: any, body: any) => {
    validateEnterprise(body);
    return await editEnterprise(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */