import {
    findAllEnterprise,
    findEnterpriseById,
    findAllEnterprisePaged,
} from '../../_services/enterprise.service';

export const findAllEnterpriseEvent = async () => {
    return await findAllEnterprise();
}

export const findEnterpriseByIdEvent = async (id: any) => {
    return await findEnterpriseById(id);
}

export const findAllEnterprisePagedEvent = async (page: any, limit: any = 8) => {
    return await findAllEnterprisePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */