import { EnterpriseType } from "./type";

export const validateEnterprise = (body: EnterpriseType) => {
    const { name } = body;
    if(name === undefined || name === '') throw new Error(`Nombre vacío`);
}

export const transformEntityEnterprise = (entity: EnterpriseType) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyEnterprise = (): EnterpriseType => {
    return {
        name: '',
        address: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */