import { EnterpriseType } from "./type";

export const validateEnterprise = (body: EnterpriseType) => {
    const { nit, name } = body;
    if(nit === undefined || nit === '') throw new Error(`NIT vacío`);
    if(name === undefined || name === '') throw new Error(`Nombre vacío`);
}

export const transformEntityEnterprise = (entity: EnterpriseType) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyEnterprise = (): EnterpriseType => {
    return {
        name: '',
        nit: '',
        address: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */