import {
    createEmployee,
    editEmployee,
} from '../../_services/employee.service';
import { validateEmployee } from './model';

export const createEmployeeEvent = async (body) => {
    validateEmployee(body);
    return await createEmployee(body);
}

export const editEmployeeEvent = async (id, body) => {
    validateEmployee(body);
    return await editEmployee(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */