import {
    findAllEmployee,
    findEmployeeById,
    findAllEmployeePaged,
    findAllEmployeeByEnterprise,
    readEmployeesExcel,
} from '../../_services/employee.service';

export const findAllEmployeeEvent = async () => {
    return await findAllEmployee();
}

export const findEmployeeByIdEvent = async (id: string) => {
    return await findEmployeeById(id);
}

export const findAllEmployeePagedEvent = async (page: number, limit: number = 8) => {
    return await findAllEmployeePaged(page, limit);
}

export const findAllEmployeeByEnterpriseEvent = async (enterprise: number) => {
    return await findAllEmployeeByEnterprise(enterprise);
}

export const readEmployeesExcelEvent = async (bytes: string) => {
    return await readEmployeesExcel({bytes})
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */