import {
    findAllEmployee,
    findEmployeeById,
    findAllEmployeePaged,
} from '../../_services/employee.service';

export const findAllEmployeeEvent = async () => {
    return await findAllEmployee();
}

export const findEmployeeByIdEvent = async (id: string) => {
    return await findEmployeeById(id);
}

export const findAllEmployeePagedEvent = async (page: number, limit: number = 8) => {
    return await findAllEmployeePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */