import { EmployeeType } from "./type";

export const validateEmployee = (body: EmployeeType) => {
    const { name, id, phone, salary, password, state, range } = body;
    if(name === '' || name === undefined) throw new Error(`Nombre vacío`);
    if(id === '' || id === undefined) throw new Error(`ID vacío`);
    if(phone === '' || phone === undefined) throw new Error(`Teléfono vacío`);
    if(salary === 0 || salary === undefined) throw new Error(`Salario vacío`);
    if(! body.uuid && (password === '' || password === undefined)) throw new Error(`Contraseña vacío`);
    if(state === undefined) throw new Error(`Estado vacío`);
    if(range === '' || range === undefined) throw new Error(`Rango asociado vacío`);
}

export const transformEntityEmployee = (entity: EmployeeType) => {
    let newEnt = {...entity}
    delete newEnt.password;
    if(typeof newEnt.range === 'object') newEnt.range = newEnt.range?.uuid;
    return newEnt;
}

export const buildEmptyEmployee = (): EmployeeType => {
    return {
        uuid: '',
        name: '',
        id: '',
        phone: '',
        salary: 0,
        password: '',
        state: 1,
        range: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */