import { EmployeeType } from "./type";

export const validateEmployee = (body: EmployeeType) => {
    //const {  } = body;
}

export const transformEntityEmployee = (entity: EmployeeType) => {
    let newEnt = {...entity}
    if(typeof newEnt.range === 'object') newEnt.range = newEnt.range?.uuid;
    return newEnt;
}

export const buildEmptyEmployee = (): EmployeeType => {
    return {
        uuid: '',
        name: '',
        id: '',
        phone: '',
        salary: 0,
        password: '',
        state: 1,
        range: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */