export const validateEmployee = (body) => {
    //const {  } = body;
}

export const transformEntityEmployee = (entity) => {
    let newEnt = {...entity}
    newEnt.range = newEnt.range?.uuid;
    return newEnt;
}

export const buildEmptyEmployee = () => {
    return {
        uuid: '',
        name: '',
        id: '',
        phone: '',
        salary: '',
        password: '',
        state: '',
        range: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */