import {
    createRangeAmount,
    editRangeAmount,
} from '../../_services/range_amount.service';
import { validateRangeAmount } from './model';

export const createRangeAmountEvent = async (body) => {
    validateRangeAmount(body);
    return await createRangeAmount(body);
}

export const editRangeAmountEvent = async (id, body) => {
    validateRangeAmount(body);
    return await editRangeAmount(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */