import {
    createRangeAmount,
    editRangeAmount,
} from '../../_services/range_amount.service';
import { validateRangeAmount } from './model';
import { RangeAmountType } from './type';

export const createRangeAmountEvent = async (body: RangeAmountType) => {
    validateRangeAmount(body);
    return await createRangeAmount(body);
}

export const editRangeAmountEvent = async (id: string, body: RangeAmountType) => {
    validateRangeAmount(body);
    return await editRangeAmount(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */