import {
    findAllRangeAmount,
    findRangeAmountById,
    findAllRangeAmountPaged,
} from '../../_services/range_amount.service';

export const findAllRangeAmountEvent = async () => {
    return await findAllRangeAmount();
}

export const findRangeAmountByIdEvent = async (id) => {
    return await findRangeAmountById(id);
}

export const findAllRangeAmountPagedEvent = async (page, limit = 8) => {
    return await findAllRangeAmountPaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */