import { RangeAmountType } from "./type";

export const validateRangeAmount = (body: RangeAmountType) => {
    //const {  } = body;
}

export const transformEntityRangeAmount = (entity: RangeAmountType) => {
    let newEnt = {...entity}
    if(typeof newEnt.amount === 'object') newEnt.amount = newEnt.amount?.uuid;
    if(typeof newEnt.range === 'object') newEnt.range = newEnt.range?.uuid;
    return newEnt;
}

export const buildEmptyRangeAmount = (): RangeAmountType => {
    return {
        uuid: '',
        amount: '',
        range: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */